papercity/accounts/urls.py
from django.urls import path
from . import views
from django.views.generic import ListView
from django.conf.urls import url
from papercity_app.models import Books

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.registerPage, name="register"),
    path('login/', views.loginPage, name="login"),
    path('logout/', views.logoutUser, name="logout"),
    url(r'^profile/$', views.edit, name='profile'),
    path("password_reset/", views.password_reset_request, name="password_reset"),
    url(r'^password/$', views.change_password, name='change_password'),
]

papercity/papercity/urls.py
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('papercity_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password/password_reset_confirm.html"),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password/password_reset_complete.html'),
         name='password_reset_complete'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

papercity/papercity_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name=''),
    path('home/', views.home, name='home'),
    path("search/", views.Search.as_view(), name="search"),
    path('book_list/', views.BookView.as_view()),
    path('book_list/<slug:slug>', views.BookDetailView.as_view(), name="book_detail"),
    path('categories/<slug:url>/', views.BookView.category_list, name="category_list"),
    path('review/<int:pk>', views.AddReview.as_view(), name="add_review"),
    path('home/selections/selection1', views.selection1, name='selection1'),
    path('home/selections/selection2', views.selection2, name='selection2'),
    path('home/selections/selection3', views.selection3, name='selection3'),
    path('home/selections/selection4', views.selection4, name='selection4'),
    path('home/stocks', views.stocks, name='stocks'),
    path('home/selection_all', views.selection_all, name='selection_all'),
    path('cart/', views.add_to_cart, name='cart'),
    path('get_cart_data/', views.get_cart_data, name='get_cart_data'),
    path('change_quan/', views.change_quan, name='change_quan'),
    path('home/terms', views.terms, name='terms'),

]

papercity/papercity_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

class Category(models.Model):
    """Категории"""
    name = models.CharField(max_length=50)
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("category_list", kwargs={"slug": self.url})

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

class Author(models.Model):
    """Авторы"""
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Автор'
        verbose_name_plural = 'Авторы'

class Genre(models.Model):
    name = models.CharField(max_length=50)
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Жанр'
        verbose_name_plural = 'Жанры'

class Books(models.Model):
    """Книги"""
    id = models.IntegerField
    title = models.CharField('Название', max_length=50)
    author = models.ManyToManyField(Author, verbose_name='автор')
    genre = models.ManyToManyField(Genre, verbose_name='жанр')
    description = models.TextField(max_length=3000)
    price = models.PositiveIntegerField('Стоимость', default=0)
    count = models.PositiveIntegerField('В наличии', default=1)
    photo = models.ImageField(upload_to="books/%Y/%m/%d/")
    category = models.ForeignKey(
        Category, verbose_name='Категория', on_delete=models.SET_NULL, null=True
    )
    url = models.SlugField(max_length=130, unique=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("book_detail", kwargs={"slug": self.url})

    class Meta:
        verbose_name = 'Книга'
        verbose_name_plural = 'Книги'

class Reviews(models.Model):
    """Отзывы"""
    email = models.EmailField
    name = models.CharField('Имя', max_length=100)
    text = models.TextField('Сообщение', max_length=5000)
    parent = models.ForeignKey(
        'self', verbose_name='Родитель', on_delete=models.SET_NULL, blank=True, null=True)
    book = models.ForeignKey(Books, verbose_name='книга', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} - {self.book}"

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'

class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Books, on_delete=models.CASCADE)
    count = models.IntegerField("Количество")
    status = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

papercity/papercity_app/forms.py
from django import forms
from .models import Reviews

class ReviewForm(forms.ModelForm):
    """Форма отзывов"""
    class Meta:
        model = Reviews
        fields = ("name", "text")

papercity/papercity_app/views.py
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from .models import Books, Category, Cart
from .forms import ReviewForm
from django.views.generic.base import View
from django.views.generic import ListView, DetailView
from django.contrib.auth.models import User
from django.http import JsonResponse, HttpResponse


class Search(ListView):
    model = Books
    template_name = 'papercity_app/search.html'

    def get_queryset(self):
        try:
            query = self.request.GET.get('q')
            a = "".join(query[0].upper()) + query[1:]
            object_list = Books.objects.filter(Q(title__icontains=a) | Q(author__name__icontains=a))
            return object_list
        except IndexError:
            pass


class BookView(ListView):
    """Список книг"""

    model = Books
    template_name = "papercity_app/book_list.html"
    context_object_name = "book_list"

    def get_queryset(self):
        return Books.objects.order_by('-id')

    def category_list(request, url):
        books = Books.objects.filter(category__url=url)
        category_menu = Category.objects.all()
        return render(request, "papercity_app/book_list.html", {"book_list": books, "category_menu": category_menu})


class BookDetailView(DetailView):
    """Страница с книгой"""

    model = Books
    template_name = "papercity_app/book_detail.html"
    slug_field = "url"
    context_object_name = "book"


class CategoryList(ListView):
    model = Category
    queryset = Category.objects.all()
    context_object_name = "categories"
    template_name = "papercity_app/book_list.html"


class AddReview(View):
    def post(self, request, pk):
        form = ReviewForm(request.POST)
        book = Books.objects.get(id=pk)
        if form.is_valid:
            form = form.save(commit=False)
            form.book_id = pk
            form.save()
        return redirect(book.get_absolute_url())

def add_to_cart(request):
    context = {}
    items = Cart.objects.filter(user__id=request.user.id, status=False)
    context["items"] = items

    if request.user.is_authenticated:
        if request.method == "POST":
            pid = request.POST["pid"]
            qty = request.POST["qty"]
            is_exist = Cart.objects.filter(book__id=pid, user__id=request.user.id, status=False)
            if len(is_exist) > 0:
                context["msz"] = "Товар уже добавлен в Вашу корзину"
                context["cls"] = "alert alert-warning"
            else:
                book = get_object_or_404(Books, id=pid)
                usr = get_object_or_404(User, id=request.user.id)
                c = Cart(user=usr, book=book, count=qty)
                c.save()
                context["msz"] = "{} добавлен в Вашу корзину".format(book.title)
                context["cls"] = "alert alert-success"

    return render(request, "papercity_app/cart.html", context)

def get_cart_data(request):
    items = Cart.objects.filter(user__id=request.user.id, status=False)
    total, count = 0, 0
    for item in items:
        total += float(item.book.price) * item.count
        count += int(item.count)

    res = {
        "total": total, "quan": count,
    }
    return JsonResponse(res)


def change_quan(request):
    if "count" in request.GET:
        cid = request.GET["cid"]
        qty = request.GET["count"]
        cart_obj = get_object_or_404(Cart, id=cid)
        cart_obj.count = qty
        cart_obj.save()
        return HttpResponse(cart_obj.count)

    if "delete_cart" in request.GET:
        id = request.GET["delete_cart"]
        cart_obj = get_object_or_404(Cart, id=id)
        cart_obj.delete()
        return HttpResponse(1)

def home(request):
    return render(request, 'papercity_app/home.html')


def selection1(request):
    return render(request, 'papercity_app/selection1.html')


def selection2(request):
    return render(request, 'papercity_app/selection2.html')


def selection3(request):
    return render(request, 'papercity_app/selection3.html')


def selection4(request):
    return render(request, 'papercity_app/selection4.html')


def stocks(request):
    return render(request, 'papercity_app/stocks.html')


def selection_all(request):
    return render(request, 'papercity_app/selection_all.html')


def terms(request):
    return render(request, 'papercity_app/terms.html')

papercity/papercity_app/templates/papercity_app/book.html
{% extends 'papercity_app/layout.html' %}
{% block content %}

    <br>

        {% load static %}
        <p><img src="{{book.photo.url}}" alt="" width="300" height="430" vspace="5" hspace="20"
                style="margin-left: 150px; float: left"></p>
        <div class="book_container">
        <h1><b>{{book.title}}</b></h1>
        <h5>{% for author in book.author.all %}
          {{author.name}}
          {% endfor %}</h5>
        <h4><b>{{book.price}} ₽</b></h4>
        <button style="color: white; margin-top: 10px;">Купить</button>
        <button style="color: white; margin-top: 10px;">Избранное</button>

        {% if book.count >= 10 %}
            <h5 style="color: green; margin: 10px;">! в наличии больше 10 штук</h5>
        {% else %}
            <h6 style="color: red; margin: 10px;">! осталось 5 штук</h6>
        {% endif %}

        <h4 style="margin-top: 20px"><b>Описание</b></h4>
        <p>{{ book.description }}</p>

        <h4 style="margin-top: 20px"><b>Мнения и отзывы</b></h4>
        <h5 style="margin-top: 20px"><b>Оставить свой отзыв</b></h5>

        <form  action="{% url 'add_review' book.id %}" method="post"  class="form" id="formReview">
         {% csrf_token %}
        <p>
            <label for="firstname"><span class="formTextRed">*</span> Имя:</label>
            <input type="text" name="name" id="name" />
        </p>
        <p>
            <label for="comment"><span class="formTextRed">*</span> Отзыв:</label>
            <textarea rows="10" name="text" id="text"></textarea>
        </p>
        <button style="color: white; width: 400px; margin-left: 180px">Отправить</button>
        </form>
    <br>

        {% for review in book.reviews_set.all %}
    <div class="card mb-3" style="max-width: 500px;">
        <div class="row g-0">
            <div class="col-md-4">
                <img src="https://icons-for-free.com/iconfiles/png/512/cat+icon-1320190750608450315.png" width="100" height="100" alt="...">
            </div>
        <div class="col-md-8">
        <div class="card-body">
            <h5 class="card-title">{{ review.name }}</h5>
            <p class="card-text">{{ review.text }}</p>
        </div>
        </div>
        </div>
    </div>
    {% endfor %}


    </div>
    <br>
{% endblock %}

papercity/papercity_app/templates/papercity_app/book_detail.html
{% extends 'papercity_app/layout.html' %}
{% block content %}

    <br>
        {% load static %}
        <p><img src="{{book.photo.url}}" alt="" width="300" height="490" vspace="5" hspace="20"
                style="margin-left: 150px; float: left"></p>
        <div class="book_container">
                <h5 style="font-size: 15px;"><a href="/home/" style="text-decoration: none;">Главная</a><a href="/book_list/" style="text-decoration: none;">
                    > Книги</a><a href="/categories/{{ book.category.url }}/" style="text-decoration: none;">
                    > {{ book.category.name}}</a></h5>
        <h1><b>{{book.title}}</b></h1>
        <h5>{% for author in book.author.all %}
          {{author.name}}
          {% endfor %}</h5>
        <h4><b>{{book.price}} ₽</b></h4>
        <form action="{% url 'cart' %}" method="post">
            {% csrf_token %}
            <input type="hidden" value="{{ book.id }}" name="pid">
            <input type="hidden" value="1" name="qty">
            <button type="submit" style="color: white; margin-top: 10px;">Купить</button>
        </form>
        <button style="color: white; margin-top: 10px;">Избранное</button>


        {% if book.count >= 10 %}
            <h5 style="color: green; margin: 10px;">! в наличии больше 10 штук</h5>
        {% else %}
            <h6 style="color: red; margin: 10px;">! осталось 5 штук</h6>
        {% endif %}

        <h4 style="margin-top: 20px"><b>Описание</b></h4>
        <p>{{ book.description }}</p>

        <h4 style="margin-top: 20px"><b>Мнения и отзывы</b></h4>
        <h5 style="margin-top: 20px"><b>Оставить свой отзыв</b></h5>

        <form  action="{% url 'add_review' book.id %}" method="post"  class="form" id="formReview">
         {% csrf_token %}
        <p>
            <label><span class="formTextRed">*</span> Имя:</label>
            <input type="text" name="name" id="name" />
        </p>
        <p>
            <label><span class="formTextRed">*</span> Отзыв:</label>
            <textarea rows="10" name="text" id="text"></textarea>
        </p>
        <button style="color: white; width: 400px; margin-left: 180px">Отправить</button>
        </form>
    <br>

        {% for review in book.reviews_set.all %}
    <div class="card mb-3" style="max-width: 500px;">
        <div class="row g-0">
            <div class="col-md-4">
                <img src="https://icons-for-free.com/iconfiles/png/512/cat+icon-1320190750608450315.png" width="100" height="100" alt="...">
            </div>
        <div class="col-md-8">
        <div class="card-body">
            <h5 class="card-title">{{ review.name }}</h5>
            <p class="card-text">{{ review.text }}</p>
        </div>
        </div>
        </div>
    </div>
    {% endfor %}


    </div>
    <br>
{% endblock %}

papercity/papercity_app/templates/papercity_app/book_list.html
{% extends 'papercity_app/layout.html' %}
{% block content %}
<br>
{% load booktags %}
<div id="menu">
    <h2><b>Книги</b></h2>
    <br>
    <h4>Категория</h4>
    <div id="wrapper">
        <ul class="menu">
            <li class="item1"><a href="/book_list" style="background-color: lightsteelblue;">Книги</a>
                <ul class="menu1">
                    {% get_categories %}
                </ul>
            </li>
        </ul>
        <br>
        <span class="toggle-button">
            <button style="color: white; font-size: 18px">Смотреть все категории</button>
        </span>
    </div>
</div>

    <br>

    <div id="content">
       <h3>Все книги этой категории</h3>
    <div class="row row-cols-1 row-cols-md-4 g-4">
         {% for book in book_list %}
        <div class="col">
            <div class="card" style="height: 500px; width: 235px">

            <div class="card-body">
                <a href="{{ book.get_absolute_url }}"><img src="{{book.photo.url}}" class="card-img-top" height="300" width="200" alt="..."></a>
                <a href="{{ book.get_absolute_url }}" class="card-title"><h5>{{book.title}}</h5></a>
            <p class="card-text">
                {% for author in book.author.all %}
                {{author.name}}
                {% endfor %}
            </p>
            <div class="card_footer">
                <div class="row row-cols-2">
                    <div class="col">
                        <h4><b>{{book.price}} ₽</b></h4>
                    </div>
                    <div class="col">
                        <form action="{% url 'cart' %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" value="{{ book.id }}" name="pid">
                            <input type="hidden" value="1" name="qty">
                            <button type="submit" style="margin-left: 35px;color: white;">Купить</button>
                        </form>
                    </div>
                </div>
            </div>

            </div>
        </div>
        </div>
        {% endfor %}
    </div>
    </div>



{% endblock %}

papercity/papercity_app/templates/papercity_app/books.html
{% extends 'papercity_app/layout.html' %}
{% block content %}
<br>

<div id="menu">
    <h2><b>Книги</b></h2>
    <br>
    <h4>Категория</h4>
    <div id="wrapper">
        <ul class="menu">
            <li class="item1"><a style="background-color: lightsteelblue;">Книги</a>
                <ul>
                    <li class="subitem1"><a href="/cat1">Художественная литература</a></li>
                    <li class="subitem2"><a href="/cat2">Литература для детей</a></li>
                    <li class="subitem3"><a href="/cat3">Учебная литература</a></li>
                    <li class="subitem4"><a href="/cat4">Иностранные языки</a></li>
                    <li class="subitem5"><a href="/cat5">Искусство</a></li>
                    <li class="subitem6"><a href="/cat6">Психология и эзотерика</a></li>
                    <li class="subitem7"><a href="/cat7">Медицина, здоровье, дети</a></li>
                    <li class="subitem8"><a href="/cat8">Научная литература</a></li>
                    <li class="subitem9"><a href="/cat9">История. Политика</a></li>
                </ul>
            </li>
        </ul>
        <br>
        <span class="toggle-button">
            <button style="color: white; font-size: 18px">Смотреть все категории</button>
        </span>
    </div>
</div>

    <br>

    <div id="content">
        <h3>Все книги</h3>
    <div class="row row-cols-1 row-cols-md-4 g-4">
         {% for books in book_list %}
        <div class="col">
            <div class="card" style="height: 500px; width: 235px">

            <div class="card-body">
                <a href="/{{ books.get_absolute_url }}"><img src="{{books.photo.url}}" class="card-img-top" height="280" width="200" alt="..."></a>
                <a href="/{{ books.get_absolute_url }} " class="card-title"><h5>{{books.title}}</h5></a>
            <p class="card-text">
                {% for author in books.author.all %}
                {{author.name}}
                {% endfor %}
            </p>
            <div class="card_footer">
                <div class="row row-cols-2">
                    <div class="col">
                        <h4><b>{{books.price}} ₽</b></h4>
                    </div>
                    <div class="col">
                        <button style="margin-left: 35px;color: white;">Купить</button>
                    </div>
                </div>
            </div>

            </div>
        </div>
        </div>
        {% endfor %}
    </div>
    </div>



{% endblock %}

papercity/papercity_app/templates/papercity_app/cart.html
{% extends 'papercity_app/layout.html' %}

{% block content %}
<div class="container">
    {% if user.is_superuser %}
        <h1 style="padding: 20px; text-align: center">Корзина админа?</h1>
    {% else %}

        {% if status %}
            <h1 style="padding: 20px; text-align: center">{{ status }}</h1>
        {% else %}
            <h1 style="padding: 10px; text-align: center">Моя корзина ({{items|length}})</h1>
        {% endif %}

    {% endif %}

    {% if user.is_authenticated %}
    <div class="row">
        <div class="col-md-9 my-5" style="box-shadow: 0 0 10px gray;">
            {% if msz %}
                <br>
                <div class="{{ cls }}">{{ msz }}</div>
            {% endif %}

            <table class="table cart">
                <thead>
                    <tr>
                        <th>Фотография</th>
                        <th>Название</th>
                        <th>Стоимость</th>
                        <th>Количество</th>
                        <th>Действие</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in items %}
                        <tr id="row{{item.id}}">
                            <td><img src="{{ item.book.photo.url }}" width="160" height="250"></td>
                            <td>{{ item.book.title }}</td>
                            <td>{{ item.book.price }} &#8381</td>
                            <td>
                            <div class="row" style="width: 150px">
                                <div class="col-md-3">
                                    <i class="fa fa-plus" style="margin-top: 10px" onclick="change_quan('{{item.id}}','plus')"></i>
                                </div>
                                <div class="col-md-6">
                                    <input type="number" value="{{ item.count }}" class="form-control" id="cart{{item.id}}">
                                </div>
                                <div class="col-md-3">
                                    <i class="fa fa-minus" style="margin-top: 10px" onclick="change_quan('{{item.id}}','minus')"></i>
                                </div>
                            </div>
                            </td>
                            <td><button onclick="remove_cart('{{item.id}}')" class="btn btn-danger">Удалить</button></td>
                        </tr>

                    {% endfor %}
                </tbody>
            </table>
        </div>

        <div class="col-md-3 my-5">
               <div style="box-shadow:0 0 10px gray;">
               <h2 class="text-center">ИТОГ</h2>
            <table class="table">
                <tr>
                    <td>Количество</td>
                    <td id="quantity"></td>
                </tr>
                <tr>
                    <td>Доставка</td>
                    <td>БЕСПЛАТНО</td>
                </tr>

                <tr>
                    <td>ОБЩИЙ ИТОГ</td>
                    <td id="grand_total"></td>
                </tr>

            </table>
            <div class="p-3">
                <a href="#">
                <button type="submit" style="color: white; margin-top: 10px; width: 100%">Приступить к оплате
                <span id="btamt"></span></button>
                </a>
            </div>
        </div>
           </div>

    </div>
    <script>
        function grandTotal(){
           $.ajax({
               url:"{% url 'get_cart_data' %}",
               type:'get',
               success:function(data){
                   save = data.total;
                   $("#item_total").html(data.total + " &#8381;");
                    $("#quantity").html(data.quan +" шт.");
                    $("#grand_total").html(data.total + " &#8381;");
                    $("#btamt").html(data.total + " &#8381;");

               }
           })
       }
       grandTotal();


       function change_quan(id,action){
           let old = $("#cart"+id).val();

           quan = 0
           if(action=="plus"){
               quan += parseInt(old)+1
           }else{
               quan += parseInt(old)-1
           }

           $("#cart"+id).val(quan);

           $.ajax({
               url:"{% url 'change_quan' %}",
               type:"get",
               data:{cid:id, count:quan},
               success:function(data){
                   grandTotal();
                 if(data==0){
                    remove_cart(id);
                 }
               }
           })
       }

       function remove_cart(id){
           $.ajax({
               url:"{% url 'change_quan' %}",
               data:{delete_cart:id},
               success:function(data){
                    grandTotal();
                    $("#row"+id).hide();
               }

           })
       }
    </script>
    {% endif %}
</div>
{% endblock %}

papercity/papercity_app/templates/papercity_app/home.html
{% extends 'papercity_app/layout.html' %}
{% block content %}
{% load static %}
<div class="container">
  <br>
 <div class="slider">
      <div class="slides">
        <!--radio buttons start-->
        <input type="radio" name="radio-btn" id="radio1">
        <input type="radio" name="radio-btn" id="radio2">
        <input type="radio" name="radio-btn" id="radio3">
        <!--radio buttons end-->
        <!--slide images start-->
        <div class="slide first">
          <img src="{% static 'img/sliders/1.jpg' %}" alt="" width="1300" height="300">
        </div>
        <div class="slide">
          <img src="{% static 'img/sliders/2.jpg' %}" alt="" width="1300" height="300">
        </div>
        <div class="slide">
          <img src="{% static 'img/sliders/3.jpg' %}" alt="" width="1300" height="300">
        </div>
        <!--slide images end-->
        <!--automatic navigation start-->
        <div class="navigation-auto">
          <div class="auto-btn1"></div>
          <div class="auto-btn2"></div>
          <div class="auto-btn3"></div>
        </div>
        <!--automatic navigation end-->
      </div>
      <!--manual navigation start-->
      <div class="navigation-manual">
        <label for="radio1" class="manual-btn"></label>
        <label for="radio2" class="manual-btn"></label>
        <label for="radio3" class="manual-btn"></label>
      </div>
      <!--manual navigation end-->
    </div>
  <br>
</div>
{% load booktags %}
{% get_new_books %}
  <div class="container1">
    <div class="row row-cols-2">
      <div class="col">
      <h2><b>Подборки книг</b></h2>
      </div>
      <div class="col">
        <a href="/home/selection_all" style="float: right;"><h5>Смотреть все →</h5></a>
      </div>
    </div>
      <div class="row row-cols-1 row-cols-md-2 g-4">
  <div class="col">
    <div class="card">
      <img src="{% static 'img/compilations/1.jpg' %}"  class="card-img" alt="...">
      <div class="card-body">
        <a class="card-title" href="selections/selection1"><h5>Художественные книги о врачах</h5></a>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card">
      <img src="{% static 'img/compilations/2.jpg' %}" class="card-img-top" alt="...">
      <div class="card-body">
        <a class="card-title" href="selections/selection2"><h5>Гарри Поттер</h5></a>
      </div>
    </div>
  </div>
        <div class="col">
    <div class="card">
      <img src="{% static 'img/compilations/3.jpg' %}" class="card-img-top" alt="...">
      <div class="card-body">
        <a class="card-title" href="selections/selection3"><h5>Ясная поляна - 2021</h5></a>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card">
      <img src="{% static 'img/compilations/4.jpg' %}" class="card-img-top" alt="...">
      <div class="card-body">
        <a class="card-title" href="selections/selection4"><h5>Жуткие романы в жанре хоррор</h5></a>
      </div>
    </div>
  </div>
      </div>
  </div>
  <br>

  <div class="container1">
    <div class="row row-cols-2">
      <div class="col">
        <h2><b>Акции</b></h2>
      </div>
      <div class="col">
        <a href="/home/stocks" style="float: right;"><h5>Смотреть все →</h5></a>
      </div>
    </div>
  <div class="row row-cols-1 row-cols-md-3 g-4">
  <div class="col">
      <div class="card bg-dark text-white">
      <img src="{% static 'img/promo/2.jpg' %}"  class="card-img" alt="...">
      </div>
  </div>
  <div class="col">
    <div class="card bg-dark text-white">
      <img src="{% static 'img/promo/1.jpg' %}" class="card-img" alt="...">
    </div>
  </div>
  <div class="col">
    <div class="card bg-dark text-white">
      <img src="{% static 'img/promo/3.jpg' %}" class="card-img" alt="...">

    </div>
  </div>
  </div>


  </div>
  <br>



{% endblock %}

papercity/papercity_app/templates/papercity_app/search.html
{% extends 'papercity_app/layout.html' %}
{% block content %}
{% load booktags %}
<br>

<div id="menu">
    <h2><b>Книги</b></h2>
    <br>
    <h4>Категория</h4>
    <div id="wrapper">
        <ul class="menu">
            <li class="item1"><a href="/book_list" style="background-color: lightsteelblue;">Книги</a>
                <ul class="menu1">
                    {% get_categories %}
                </ul>
            </li>
        </ul>
        <br>
        <span class="toggle-button">
            <button style="color: white; font-size: 18px">Смотреть все категории</button>
        </span>
    </div>
</div>

    <br>

    <div id="content">
        <h3>Результаты поиска</h3>
        {% if object_list %}
    <div class="row row-cols-1 row-cols-md-4 g-4">
         {% for book in object_list %}
        <div class="col">
            <div class="card" style="height: 500px; width: 235px">

            <div class="card-body">
                <a href="{{ book.get_absolute_url }}"><img src="{{book.photo.url}}" class="card-img-top" height="300" width="200" alt="..."></a>
                <a href="{{ book.get_absolute_url }}" class="card-title"><h5>{{book.title}}</h5></a>
            <p class="card-text">
                {% for author in book.author.all %}
                {{author.name}}
                {% endfor %}
            </p>
            <div class="card_footer">
                <div class="row row-cols-2">
                    <div class="col">
                        <h4><b>{{book.price}} ₽</b></h4>
                    </div>
                    <div class="col">
                        <button style="margin-left: 35px;color: white;">Купить</button>
                    </div>
                </div>
            </div>

            </div>
        </div>
        </div>
         {% endfor %}
          {% else %}
        <br>
        <h4>По данному запросу ничего не найдено</h4>
        <h5>Попробуйте дополнить запрос: укажите автора или добавьте ключевые слова, связанные с товаром.</h5>
        <br>
        <h4><b>Рекомендации</b></h4>
        {% get_empty_books %}
        <br>
        {% endif %}
    </div>
    </div>
{% endblock %}